from datetime import datetime
from db.models import db, Article
from app import app

with app.app_context():
    db.create_all()

    articles = [
        Article(
            title="Local Man Claims to Be Time Traveler, Only Predicts Weather",
            description="A local man baffled residents by claiming he's from the year 2147, but could only predict the next day's rain.",
            content="Residents of Pinecone Valley were left amused when local man Barry 'The Time Nomad' Jenkins claimed he was from the year 2147. When asked for insights into the future, Jenkins could only state that 'it's probably going to drizzle tomorrow.' Coincidentally, it did rain the next day.",
            html="<p>Residents of Pinecone Valley were left amused when local man Barry 'The Time Nomad' Jenkins claimed he was from the year 2147. When asked for insights into the future, Jenkins could only state that 'it's probably going to drizzle tomorrow.' Coincidentally, it did rain the next day.</p>",
            authors=["Barry's Lawyer"],
            tags=["local news", "remarkable"],
            datetime_made=datetime.now(),
            datetime_edited=datetime.now(),
            cover_image_id=None,
        ),
        Article(
            title="Cat Elected Mayor in Unopposed Write-In Campaign",
            description="A feline named Chairman Meow has become mayor of a small town after an accidental campaign.",
            content="In an unprecedented electoral upset, a cat named Chairman Meow became mayor of the sleepy town of Furburg. Locals say the campaign started as a joke, but with no other candidates on the ballot, the 4-year-old tabby secured a landslide victory. His first act was to nap through his own inauguration.",
            html="<p>In an unprecedented electoral upset, a cat named Chairman Meow became mayor of the sleepy town of Furburg. Locals say the campaign started as a joke, but with no other candidates on the ballot, the 4-year-old tabby secured a landslide victory. His first act was to nap through his own inauguration.</p>",
            authors=["E. Pawlson"],
            tags=["politics"],
            datetime_made=datetime.now(),
            datetime_edited=datetime.now(),
            cover_image_id=None,
        ),
        Article(
            title="Scientists Discover Sandwich Missing Since 1983",
            description="The legendary 'library lunch' has been found behind a bookshelf during renovations.",
            content="Construction workers renovating the Eastside Public Library made a shocking discovery: a peanut butter and jelly sandwich believed to have been lost in 1983. Perfectly mummified between outdated encyclopedias, the sandwich has sparked interest among local historians and mold enthusiasts.",
            html="<p>Construction workers renovating the Eastside Public Library made a shocking discovery: a peanut butter and jelly sandwich believed to have been lost in 1983. Perfectly mummified between outdated encyclopedias, the sandwich has sparked interest among local historians and mold enthusiasts.</p>",
            authors=["Sandra Crumbly"],
            tags=["history"],
            datetime_made=datetime.now(),
            datetime_edited=datetime.now(),
            cover_image_id=None,
        ),
        Article(
            title="Town Holds Annual Invisible Parade",
            description="Residents lined empty streets to celebrate tradition.",
            content="The town of Windmere held its 57th Annual Invisible Parade, with thousands lining the streets to watch absolutely nothing go by. Mayor Sanders praised the event as 'the least disruptive parade we've ever had.'",
            html="<p>The town of Windmere held its 57th Annual Invisible Parade, with thousands lining the streets to watch absolutely nothing go by. Mayor Sanders praised the event as 'the least disruptive parade we've ever had.'</p>",
            authors=["J. Holloway"],
            tags=["culture", "local news"],
            datetime_made=datetime.now(),
            datetime_edited=datetime.now(),
            cover_image_id=None,
        ),
        Article(
            title="Man Claims His Reflection is Taunting Him",
            description="A local man insists his mirror image is making faces at him.",
            content="Dennis Rundle has refused to enter his bathroom for three days, claiming his reflection has developed a mind of its own. Experts say it's likely sleep deprivation, but Rundle remains convinced the mirror 'winked mockingly.'",
            html="<p>Dennis Rundle has refused to enter his bathroom for three days, claiming his reflection has developed a mind of its own. Experts say it's likely sleep deprivation, but Rundle remains convinced the mirror 'winked mockingly.'</p>",
            authors=["N. Silver"],
            tags=["remarkable", "local news"],
            datetime_made=datetime.now(),
            datetime_edited=datetime.now(),
            cover_image_id=None,
        ),
        Article(
            title="Library Introduces 'Speed Reading' by Firing Books from Cannon",
            description="A bold new approach to literacy is making waves.",
            content="The Rivertown Library has unveiled a controversial 'Speed Reading' program that involves firing books from a small cannon at patrons. Librarians claim it's an 'immersive experience,' though local doctors disagree.",
            html="<p>The Rivertown Library has unveiled a controversial 'Speed Reading' program that involves firing books from a small cannon at patrons. Librarians claim it's an 'immersive experience,' though local doctors disagree.</p>",
            authors=["M. Page"],
            tags=["education", "remarkable"],
            datetime_made=datetime.now(),
            datetime_edited=datetime.now(),
            cover_image_id=None,
        ),
        Article(
            title="Pigeon Starts Blog About City Life",
            description="A local pigeon has attracted thousands of readers with its urban musings.",
            content="A pigeon known as Gerald has become an internet sensation for his blog detailing life on the city streets. Posts include reviews of park benches and stern warnings about 'the giant pretzel thief.'",
            html="<p>A pigeon known as Gerald has become an internet sensation for his blog detailing life on the city streets. Posts include reviews of park benches and stern warnings about 'the giant pretzel thief.'</p>",
            authors=["A. Beaks"],
            tags=["technology"],
            datetime_made=datetime.now(),
            datetime_edited=datetime.now(),
            cover_image_id=None,
        ),
        Article(
            title="World's Quietest Rock Band Releases Silent Album",
            description="The band 'Mute Uprising' pushes artistic boundaries with an entirely silent release.",
            content="Critics are divided over Mute Uprising's new album, which features 12 tracks of pure silence. The band insists it's a commentary on 'the noise of society.' Fans say it's great for meditation.",
            html="<p>Critics are divided over Mute Uprising's new album, which features 12 tracks of pure silence. The band insists it's a commentary on 'the noise of society.' Fans say it's great for meditation.</p>",
            authors=["D. Soundless"],
            tags=["culture"],
            datetime_made=datetime.now(),
            datetime_edited=datetime.now(),
            cover_image_id=None,
        ),
        Article(
            title="Area Man Builds World's Largest Rubber Band Ball, Forgets Why",
            description="He started the project during lockdown and lost all motivation.",
            content="Mark Tevis spent 18 months building a 9-foot rubber band ball in his garage. When asked why, he simply replied, 'I don't know anymore.' Neighbors worry about its structural integrity.",
            html="<p>Mark Tevis spent 18 months building a 9-foot rubber band ball in his garage. When asked why, he simply replied, 'I don't know anymore.' Neighbors worry about its structural integrity.</p>",
            authors=["S. Tretch"],
            tags=["local news", "remarkable"],
            datetime_made=datetime.now(),
            datetime_edited=datetime.now(),
            cover_image_id=None,
        ),
        Article(
            title="Scientists Train Worms to Form Conga Line",
            description="Breakthrough in worm choreography stuns community.",
            content="A team at Eastfield University claims they've trained earthworms to move in perfect conga-line formation. Lead researcher Dr. Mabel Chong calls it 'a testament to patience, bribery, and lettuce.'",
            html="<p>A team at Eastfield University claims they've trained earthworms to move in perfect conga-line formation. Lead researcher Dr. Mabel Chong calls it 'a testament to patience, bribery, and lettuce.'</p>",
            authors=["Dr. Mabel Chong"],
            tags=["science"],
            datetime_made=datetime.now(),
            datetime_edited=datetime.now(),
            cover_image_id=None,
        ),
        Article(
            title="New Dating App Matches People by Hat Size",
            description="Algorithm claims cranial compatibility is key to romance.",
            content="Startup 'HatMatch' says it has cracked the code of love by matching users purely on hat size. CEO Tim Blathers insists 'headroom compatibility' predicts relationship longevity, though critics remain skeptical.",
            html="<p>Startup 'HatMatch' says it has cracked the code of love by matching users purely on hat size. CEO Tim Blathers insists 'headroom compatibility' predicts relationship longevity, though critics remain skeptical.</p>",
            authors=["L. Hart"],
            tags=["technology"],
            datetime_made=datetime.now(),
            datetime_edited=datetime.now(),
            cover_image_id=None,
        ),
        Article(
            title="Man Sues Ghost for Back Rent",
            description="Landlord claims haunting tenant owes three years of unpaid rent.",
            content="Stanley Franks filed a lawsuit in Small Claims Court against a ghost allegedly residing in his attic. 'It's only fair,' he says, 'everyone else pays.' The ghost could not be reached for comment.",
            html="<p>Stanley Franks filed a lawsuit in Small Claims Court against a ghost allegedly residing in his attic. 'It's only fair,' he says, 'everyone else pays.' The ghost could not be reached for comment.</p>",
            authors=["C. Specter"],
            tags=["legal", "remarkable"],
            datetime_made=datetime.now(),
            datetime_edited=datetime.now(),
            cover_image_id=None,
        ),
        Article(
            title="Local Gym Offers Membership for Pets",
            description="Owners say their cats and dogs deserve fitness too.",
            content="Paws & Reps, a new gym in downtown Elmwood, has launched classes for dogs, cats, and even parrots. Owner Jenna Mills says pets love the treadmill, though cats mostly sit on yoga mats and judge.",
            html="<p>Paws & Reps, a new gym in downtown Elmwood, has launched classes for dogs, cats, and even parrots. Owner Jenna Mills says pets love the treadmill, though cats mostly sit on yoga mats and judge.</p>",
            authors=["J. Mills"],
            tags=["economy"],
            datetime_made=datetime.now(),
            datetime_edited=datetime.now(),
            cover_image_id=None,
        ),
    ]

    for article in articles:
        article.authors = article.authors  # triggers setter
        article.tags = article.tags  # triggers setter
        db.session.add(article)

    db.session.commit()
    print("Inserted dummy articles.")
